import type { FAQ, SourceLink } from "./types";

export type DinnerIdea = {
  id: string;
  title: string;
  category: "Skillet" | "Pasta & noodles" | "Bowls" | "Tacos & wraps" | "Meatless";
  diet: string;
  minutes: number;
  activeMinutes: number;
  cookware: string;
  servings: number;
  image: string;
  imageAlt: string;
  whyFast: string;
  ingredients: string[];
  method: { title: string; text: string }[];
  finishCue: string;
  swap: string;
  safety?: string;
};

export const dinnerIdeas: DinnerIdea[] = [
  {
    id: "lemon-garlic-chicken-cutlets",
    title: "Lemon-Garlic Chicken Cutlets",
    category: "Skillet",
    diet: "High protein",
    minutes: 20,
    activeMinutes: 18,
    cookware: "1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-skillet.webp",
    imageAlt: "Golden lemon-garlic chicken cutlets in a green enamel skillet",
    whyFast: "Thin cutlets cook before a pan sauce can over-reduce.",
    ingredients: [
      "1½ lb chicken breast cutlets, about ½ inch thick",
      "¾ tsp fine salt and ½ tsp black pepper",
      "2 tbsp all-purpose flour",
      "2 tbsp olive oil",
      "3 garlic cloves, finely chopped",
      "¾ cup low-sodium chicken stock",
      "1 lemon: 2 tbsp juice plus zest",
      "1 tbsp cold butter and 2 tbsp chopped parsley",
    ],
    method: [
      { title: "Season", text: "Pat the cutlets dry, season and dust with a very thin layer of flour." },
      { title: "Sear", text: "Heat oil over medium-high. Cook in one layer until golden, turning once; transfer as each piece reaches doneness." },
      { title: "Sauce", text: "Lower heat, cook garlic 20 seconds, add stock and reduce by half. Return chicken, add lemon, then swirl in cold butter and parsley." },
    ],
    finishCue: "Sauce lightly coats a spoon and every cutlet reaches 165°F in its thickest point.",
    swap: "Use thin pork cutlets and follow the appropriate whole-cut pork temperature guidance.",
    safety: "USDA guidance: all poultry should reach 165°F (74°C).",
  },
  {
    id: "turkey-zucchini-skillet",
    title: "Turkey, Zucchini & Feta Skillet",
    category: "Skillet",
    diet: "High protein",
    minutes: 25,
    activeMinutes: 20,
    cookware: "1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-skillet.webp",
    imageAlt: "Ground turkey and zucchini skillet finished with feta and herbs",
    whyFast: "Ground turkey and small zucchini pieces brown quickly in the same pan.",
    ingredients: [
      "1 tbsp olive oil",
      "1 lb ground turkey",
      "1 small red onion, diced",
      "2 medium zucchini, ½-inch dice",
      "2 tsp dried oregano and ½ tsp smoked paprika",
      "1 cup cherry tomatoes, halved",
      "½ cup crumbled feta",
      "1 lemon and chopped dill or parsley",
    ],
    method: [
      { title: "Brown", text: "Heat oil and spread turkey in the pan. Leave it undisturbed for 2 minutes, then break it into small pieces." },
      { title: "Cook vegetables", text: "Add onion, zucchini, oregano and paprika. Cook until zucchini is tender with browned edges." },
      { title: "Finish", text: "Fold in tomatoes for 2 minutes. Remove from heat and add feta, lemon zest, lemon juice and herbs." },
    ],
    finishCue: "Turkey is fully cooked to 165°F and zucchini is tender without releasing a pool of water.",
    swap: "Use ground chicken with the same 165°F safety endpoint, or crumbled extra-firm tofu for a meatless version.",
    safety: "Ground poultry should reach 165°F (74°C).",
  },
  {
    id: "sausage-pepper-gnocchi",
    title: "Sausage, Pepper & Crisp Gnocchi",
    category: "Skillet",
    diet: "Family-friendly",
    minutes: 25,
    activeMinutes: 22,
    cookware: "1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-skillet.webp",
    imageAlt: "Crisp gnocchi with sausage, peppers and basil in a skillet",
    whyFast: "Shelf-stable gnocchi crisps directly in the skillet; no pasta pot is required.",
    ingredients: [
      "12 oz fully cooked chicken sausage, sliced",
      "1 tbsp olive oil",
      "1 lb shelf-stable potato gnocchi",
      "1 red bell pepper, thinly sliced",
      "1 small onion, thinly sliced",
      "½ cup water",
      "2 cups baby spinach",
      "¼ cup grated Parmesan and torn basil",
    ],
    method: [
      { title: "Brown sausage", text: "Sear sliced sausage in oil until the cut faces are golden; move to a plate." },
      { title: "Crisp gnocchi", text: "Add gnocchi, peppers and onion. Cook 5 minutes, add water, cover 3 minutes, then uncover and crisp." },
      { title: "Combine", text: "Return sausage, fold in spinach until wilted and finish with Parmesan and basil." },
    ],
    finishCue: "Gnocchi is tender inside, browned outside and the sausage is steaming hot throughout.",
    swap: "Use plant-based sausage or mushrooms; check the product package for safe reheating directions.",
  },
  {
    id: "egg-roll-in-a-bowl",
    title: "Ginger Turkey Egg Roll Bowl",
    category: "Skillet",
    diet: "Lower carb",
    minutes: 25,
    activeMinutes: 20,
    cookware: "1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-skillet.webp",
    imageAlt: "Ginger turkey and cabbage egg roll bowl with scallions",
    whyFast: "Bagged slaw eliminates most knife work and wilts in minutes.",
    ingredients: [
      "1 tbsp neutral oil",
      "1 lb ground turkey",
      "1 tbsp grated ginger",
      "3 garlic cloves, grated",
      "14 oz coleslaw mix",
      "3 tbsp low-sodium soy sauce",
      "1 tbsp rice vinegar",
      "1 tsp toasted sesame oil",
      "Scallions and sesame seeds",
    ],
    method: [
      { title: "Brown", text: "Heat oil and cook turkey, breaking it into small pieces, until no raw patches remain." },
      { title: "Aromatics", text: "Add ginger and garlic; stir for 30 seconds. Add slaw in two batches so the pan stays hot." },
      { title: "Glaze", text: "Add soy sauce and vinegar, cook until cabbage is crisp-tender, then finish off heat with sesame oil and scallions." },
    ],
    finishCue: "Turkey reaches 165°F and cabbage is wilted but still has bite.",
    swap: "Use crumbled tempeh; add 2 tablespoons water with the sauce if the pan looks dry.",
    safety: "Ground turkey should reach 165°F (74°C).",
  },
  {
    id: "creamy-tomato-tortellini",
    title: "Creamy Tomato Tortellini with Spinach",
    category: "Pasta & noodles",
    diet: "Vegetarian",
    minutes: 20,
    activeMinutes: 12,
    cookware: "1 pot",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-pasta.webp",
    imageAlt: "Creamy tomato cheese tortellini with spinach and Parmesan",
    whyFast: "Refrigerated tortellini cooks directly in a measured sauce.",
    ingredients: [
      "1 tbsp olive oil",
      "3 garlic cloves, sliced",
      "2 tbsp tomato paste",
      "1 can (14½ oz) crushed tomatoes",
      "2 cups low-sodium vegetable stock",
      "18–20 oz refrigerated cheese tortellini",
      "⅓ cup heavy cream",
      "3 cups baby spinach",
      "¼ cup Parmesan and red-pepper flakes",
    ],
    method: [
      { title: "Build base", text: "Cook garlic in oil for 30 seconds. Stir in tomato paste until it darkens slightly." },
      { title: "Simmer pasta", text: "Add tomatoes and stock. Bring to a lively simmer, add tortellini and cook according to package timing." },
      { title: "Finish", text: "Lower heat, stir in cream and spinach, then add Parmesan. Rest 2 minutes so the sauce clings." },
    ],
    finishCue: "Tortellini is tender, spinach is wilted and the sauce coats rather than floods the bowl.",
    swap: "Use shelf-stable tortellini and adjust liquid and timing to its package directions.",
  },
  {
    id: "miso-mushroom-noodles",
    title: "Miso-Butter Mushroom Noodles",
    category: "Pasta & noodles",
    diet: "Vegetarian",
    minutes: 20,
    activeMinutes: 18,
    cookware: "1 pot + 1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-pasta.webp",
    imageAlt: "Glossy miso mushroom noodles with scallions",
    whyFast: "Fresh noodles cook while mushrooms brown in a wide skillet.",
    ingredients: [
      "12 oz fresh ramen, udon or thin wheat noodles",
      "12 oz sliced cremini mushrooms",
      "1 tbsp neutral oil",
      "2 tbsp unsalted butter",
      "2 tbsp white miso",
      "1 tbsp low-sodium soy sauce",
      "1 tsp rice vinegar",
      "½ cup reserved noodle water",
      "Scallions and toasted sesame seeds",
    ],
    method: [
      { title: "Brown mushrooms", text: "Spread mushrooms in hot oil and leave them undisturbed until the first side browns. Stir and finish cooking." },
      { title: "Cook noodles", text: "Boil noodles just until tender. Reserve ½ cup water before draining." },
      { title: "Emulsify", text: "Whisk butter, miso, soy, vinegar and ¼ cup noodle water in the skillet. Toss in noodles, adding water until glossy." },
    ],
    finishCue: "Sauce looks shiny and clings in a thin layer; no dry miso lumps remain.",
    swap: "Use gluten-free rice noodles and certified gluten-free tamari and miso when needed.",
  },
  {
    id: "tuna-lemon-caper-pasta",
    title: "Lemony Tuna & Caper Pantry Pasta",
    category: "Pasta & noodles",
    diet: "Pantry meal",
    minutes: 20,
    activeMinutes: 14,
    cookware: "1 pot + 1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-pasta.webp",
    imageAlt: "Lemon tuna caper pasta with parsley and toasted crumbs",
    whyFast: "The sauce is assembled from pantry ingredients while pasta boils.",
    ingredients: [
      "12 oz spaghetti or linguine",
      "3 tbsp olive oil",
      "3 garlic cloves, thinly sliced",
      "2 cans (5 oz each) tuna in oil, drained lightly",
      "2 tbsp capers, rinsed",
      "1 lemon: zest plus 2 tbsp juice",
      "½ cup reserved pasta water",
      "¼ cup chopped parsley",
      "⅓ cup toasted breadcrumbs, optional",
    ],
    method: [
      { title: "Boil", text: "Cook pasta in salted water until just shy of al dente; reserve water." },
      { title: "Bloom", text: "Warm garlic in olive oil until fragrant, then add capers and tuna without pulverizing the flakes." },
      { title: "Toss", text: "Add pasta, lemon zest, juice and enough water to create a glossy coating. Finish with parsley and crumbs." },
    ],
    finishCue: "Pasta is al dente and tuna remains in visible flakes rather than a dry paste.",
    swap: "Use canned salmon or mashed white beans for a meatless pantry option.",
  },
  {
    id: "pesto-gnocchi-peas",
    title: "Pesto Gnocchi with Peas & Ricotta",
    category: "Pasta & noodles",
    diet: "Vegetarian",
    minutes: 15,
    activeMinutes: 10,
    cookware: "1 pot",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-pasta.webp",
    imageAlt: "Pesto potato gnocchi with green peas and ricotta",
    whyFast: "Gnocchi and frozen peas share one pot; pesto never sees harsh heat.",
    ingredients: [
      "1 lb potato gnocchi",
      "1½ cups frozen peas",
      "½ cup basil pesto",
      "½ cup whole-milk ricotta",
      "½ lemon",
      "¼ cup grated Parmesan",
      "Black pepper and ½ cup reserved cooking water",
    ],
    method: [
      { title: "Boil", text: "Cook gnocchi in salted water. Add frozen peas during the final 2 minutes." },
      { title: "Loosen pesto", text: "Whisk pesto with ¼ cup warm cooking water in the serving bowl." },
      { title: "Fold", text: "Drain, add gnocchi and peas, then fold gently. Spoon ricotta over the top and finish with lemon and Parmesan." },
    ],
    finishCue: "Pesto stays bright green and the sauce coats without an oily pool.",
    swap: "Use dairy-free pesto and almond ricotta for a plant-based version, checking labels for allergens.",
  },
  {
    id: "salmon-rice-bowls",
    title: "Ginger Salmon Rice Bowls",
    category: "Bowls",
    diet: "High protein",
    minutes: 25,
    activeMinutes: 18,
    cookware: "1 skillet + microwave",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-bowls.webp",
    imageAlt: "Ginger glazed salmon rice bowl with cucumber and edamame",
    whyFast: "Small salmon cubes cook quickly while microwave rice and edamame heat.",
    ingredients: [
      "1¼ lb skinless salmon, cut into 1½-inch cubes",
      "2 tbsp low-sodium soy sauce",
      "1 tbsp honey",
      "1 tbsp rice vinegar",
      "2 tsp grated ginger",
      "2 tsp neutral oil",
      "4 cups hot cooked or microwave rice",
      "1 cup shelled edamame and 1 sliced cucumber",
      "Scallions and sesame seeds",
    ],
    method: [
      { title: "Mix glaze", text: "Combine soy, honey, vinegar and ginger. Pat salmon dry." },
      { title: "Sear", text: "Brown salmon in oil on two sides. Add glaze and turn gently until it clings." },
      { title: "Build", text: "Divide hot rice, edamame and cucumber among bowls. Add salmon and spoon over pan glaze." },
    ],
    finishCue: "Salmon reaches 145°F or is opaque and separates easily; glaze is shiny, not burnt.",
    swap: "Use extra-firm tofu cubes; brown all sides before adding glaze.",
    safety: "USDA guidance: fish should reach 145°F (63°C) or become opaque and separate easily with a fork.",
  },
  {
    id: "shrimp-fried-rice",
    title: "Fast Shrimp Fried Rice",
    category: "Bowls",
    diet: "Freezer-friendly staples",
    minutes: 20,
    activeMinutes: 20,
    cookware: "1 wok or skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-bowls.webp",
    imageAlt: "Shrimp fried rice with peas, carrots and scallions",
    whyFast: "Cold cooked rice and frozen vegetables need only reheating and browning.",
    ingredients: [
      "1 lb peeled deveined shrimp, patted dry",
      "3 tbsp neutral oil, divided",
      "2 eggs, beaten",
      "4 cups cold cooked long-grain rice",
      "1½ cups frozen peas and carrots, thawed",
      "3 scallions, sliced",
      "3 tbsp low-sodium soy sauce",
      "1 tsp toasted sesame oil",
    ],
    method: [
      { title: "Cook shrimp", text: "Sear shrimp in 1 tablespoon oil until pearly and opaque; remove immediately." },
      { title: "Scramble", text: "Add 1 teaspoon oil, scramble eggs softly and move them to the shrimp plate." },
      { title: "Fry rice", text: "Use remaining oil to fry rice and vegetables until hot. Add soy, return shrimp and egg, then finish with sesame oil and scallions." },
    ],
    finishCue: "Shrimp is pearly and opaque, and every grain of rice is steaming hot.",
    swap: "Use diced leftover chicken and reheat the finished dish to 165°F.",
    safety: "Cook shrimp until pearly or white and opaque. Reheat leftovers to 165°F (74°C).",
  },
  {
    id: "teriyaki-tofu-bowls",
    title: "Crisp Teriyaki Tofu Bowls",
    category: "Bowls",
    diet: "Vegan",
    minutes: 25,
    activeMinutes: 22,
    cookware: "1 skillet + microwave",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-bowls.webp",
    imageAlt: "Crisp teriyaki tofu bowl with broccoli and rice",
    whyFast: "Thin tofu slabs crisp faster than cubes and glaze evenly.",
    ingredients: [
      "14–16 oz extra-firm tofu, well dried and cut into ½-inch slabs",
      "2 tbsp cornstarch",
      "2 tbsp neutral oil",
      "3 tbsp low-sodium soy sauce",
      "2 tbsp water",
      "1 tbsp maple syrup or brown sugar",
      "1 tbsp rice vinegar and 1 tsp grated ginger",
      "4 cups hot rice and 3 cups steamed broccoli",
    ],
    method: [
      { title: "Coat", text: "Season dried tofu lightly and dust both sides with a thin cornstarch layer." },
      { title: "Crisp", text: "Pan-fry in oil until both broad faces are golden and firm." },
      { title: "Glaze", text: "Add soy, water, maple, vinegar and ginger. Turn tofu until glossy, then serve with rice and broccoli." },
    ],
    finishCue: "Tofu edges are crisp and the glaze clings without dry cornstarch patches.",
    swap: "Use tempeh strips and add an extra tablespoon of water as the glaze reduces.",
  },
  {
    id: "mediterranean-chickpea-bowls",
    title: "Mediterranean Chickpea Crunch Bowls",
    category: "Bowls",
    diet: "Vegetarian · no-cook",
    minutes: 15,
    activeMinutes: 15,
    cookware: "No stove",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-bowls.webp",
    imageAlt: "Mediterranean chickpea bowl with cucumber, tomato, feta and hummus",
    whyFast: "Canned chickpeas, hummus and chopped vegetables make a complete no-cook assembly.",
    ingredients: [
      "2 cans (15 oz each) chickpeas, rinsed and drained",
      "1 English cucumber, chopped",
      "2 cups cherry tomatoes, halved",
      "½ small red onion, thinly sliced",
      "½ cup olives",
      "½ cup crumbled feta",
      "¾ cup hummus",
      "1 lemon and 2 tbsp olive oil",
      "4 warmed pitas, optional",
    ],
    method: [
      { title: "Dress", text: "Toss chickpeas, cucumber, tomatoes and onion with lemon juice, oil, salt and pepper." },
      { title: "Layer", text: "Spread hummus in each bowl, then add the chickpea mixture, olives and feta." },
      { title: "Serve", text: "Add lemon zest and pita wedges. Serve promptly or keep the dressed mixture chilled." },
    ],
    finishCue: "Vegetables remain crisp and the chickpeas are well drained, not watery.",
    swap: "Omit feta and use a dairy-free hummus for a vegan bowl.",
  },
  {
    id: "crispy-black-bean-tacos",
    title: "Crispy Black Bean Tacos",
    category: "Tacos & wraps",
    diet: "Vegetarian",
    minutes: 25,
    activeMinutes: 20,
    cookware: "1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-tacos.webp",
    imageAlt: "Crispy folded black bean tacos with cabbage and lime",
    whyFast: "A lightly mashed canned-bean filling stays put while tortillas crisp.",
    ingredients: [
      "2 cans (15 oz each) black beans, rinsed and drained",
      "½ cup salsa",
      "1 tsp ground cumin and ½ tsp smoked paprika",
      "1 cup shredded Monterey Jack or cheddar",
      "8 small corn or flour tortillas",
      "2 tbsp neutral oil",
      "2 cups shredded cabbage",
      "1 lime and cilantro",
    ],
    method: [
      { title: "Mash filling", text: "Warm beans, salsa and spices until thick. Mash about half so the mixture binds." },
      { title: "Fold", text: "Divide beans and cheese over half of each warm tortilla and fold." },
      { title: "Crisp", text: "Pan-cook in a thin oil film until both sides are golden. Serve with cabbage tossed in lime juice." },
    ],
    finishCue: "Tortillas are crisp, cheese is melted and the filling is hot without leaking water.",
    swap: "Use pinto beans or leftover lentils cooked down until thick.",
  },
  {
    id: "chicken-fajita-tacos",
    title: "Chicken Fajita Tacos",
    category: "Tacos & wraps",
    diet: "High protein",
    minutes: 25,
    activeMinutes: 22,
    cookware: "1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-tacos.webp",
    imageAlt: "Chicken fajita tacos with seared peppers, onions and lime",
    whyFast: "Thin strips maximize browned surface and reach a safe temperature quickly.",
    ingredients: [
      "1½ lb boneless skinless chicken breasts, ¼-inch strips",
      "2 bell peppers, thinly sliced",
      "1 medium onion, thinly sliced",
      "2 tbsp neutral oil, divided",
      "2 tsp chili powder and 1 tsp ground cumin",
      "½ tsp each garlic powder and fine salt",
      "8 warm tortillas",
      "1 lime, salsa and sliced avocado",
    ],
    method: [
      { title: "Sear chicken", text: "Toss chicken with half the oil and spices. Sear in a hot skillet in two batches so it browns rather than steams." },
      { title: "Cook vegetables", text: "Add remaining oil, peppers and onion. Cook until crisp-tender with charred edges." },
      { title: "Combine", text: "Return chicken until hot and verified done. Finish with lime and serve in warm tortillas." },
    ],
    finishCue: "Chicken reaches 165°F and peppers remain colorful and lightly crisp.",
    swap: "Use thin portobello strips; brown them before peppers and season at the end.",
    safety: "All poultry should reach 165°F (74°C).",
  },
  {
    id: "greek-turkey-pitas",
    title: "Greek Turkey Pitas with Yogurt Sauce",
    category: "Tacos & wraps",
    diet: "High protein",
    minutes: 25,
    activeMinutes: 20,
    cookware: "1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-tacos.webp",
    imageAlt: "Greek-spiced turkey in warm pitas with cucumber yogurt sauce",
    whyFast: "Crumbled turkey cooks faster than formed patties and drops straight into pita.",
    ingredients: [
      "1 lb ground turkey",
      "1 tbsp olive oil",
      "2 tsp dried oregano and 1 tsp ground cumin",
      "2 garlic cloves, grated",
      "1 cup plain Greek yogurt",
      "½ cucumber, grated and squeezed dry",
      "1 lemon and 2 tbsp chopped dill",
      "4 large pitas, warmed",
      "Tomato and shredded lettuce",
    ],
    method: [
      { title: "Sauce", text: "Mix yogurt, dry cucumber, half the lemon juice, dill and a pinch of salt." },
      { title: "Brown turkey", text: "Cook turkey in oil with oregano, cumin and garlic until browned and fully done." },
      { title: "Fill", text: "Season turkey with remaining lemon. Fill warm pitas with sauce, lettuce, tomato and turkey." },
    ],
    finishCue: "Turkey reaches 165°F and yogurt sauce remains cold and thick.",
    swap: "Use canned chickpeas, lightly mashed and browned with the same spices.",
    safety: "Ground turkey should reach 165°F (74°C); keep yogurt refrigerated until serving.",
  },
  {
    id: "chickpea-spinach-curry",
    title: "Coconut Chickpea & Spinach Curry",
    category: "Meatless",
    diet: "Vegan · gluten-free",
    minutes: 25,
    activeMinutes: 15,
    cookware: "1 pot",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-meatless.webp",
    imageAlt: "Coconut chickpea spinach curry with rice and lime",
    whyFast: "Canned chickpeas are already tender; the sauce only needs time to concentrate.",
    ingredients: [
      "1 tbsp neutral oil",
      "1 small onion, finely chopped",
      "3 garlic cloves and 1 tbsp grated ginger",
      "2 tbsp curry powder",
      "2 cans (15 oz each) chickpeas, rinsed",
      "1 can (14 oz) light or full-fat coconut milk",
      "1 can (14 oz) diced tomatoes, drained lightly",
      "5 oz baby spinach",
      "1 lime and hot cooked rice",
    ],
    method: [
      { title: "Bloom", text: "Cook onion in oil until soft. Add garlic, ginger and curry powder; stir until fragrant." },
      { title: "Simmer", text: "Add chickpeas, coconut milk and tomatoes. Simmer uncovered until the sauce coats a spoon." },
      { title: "Wilt", text: "Fold in spinach, season and finish with lime. Serve over hot rice." },
    ],
    finishCue: "Sauce is creamy rather than watery and spinach has just wilted.",
    swap: "Add frozen peas or use cannellini beans; drain tomatoes more thoroughly if the sauce becomes thin.",
  },
  {
    id: "white-bean-tomato-skillet",
    title: "Creamy White Bean Tomato Skillet",
    category: "Meatless",
    diet: "Vegetarian",
    minutes: 20,
    activeMinutes: 15,
    cookware: "1 skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-meatless.webp",
    imageAlt: "Creamy white beans and tomatoes in a skillet with greens",
    whyFast: "Mashing a few canned beans thickens the sauce without a long simmer.",
    ingredients: [
      "2 tbsp olive oil",
      "3 garlic cloves, sliced",
      "2 cans (15 oz each) cannellini beans, rinsed",
      "1 can (14½ oz) fire-roasted diced tomatoes",
      "½ cup vegetable stock",
      "1 tsp dried Italian herbs",
      "3 cups baby kale or spinach",
      "¼ cup grated Parmesan",
      "Toasted sourdough for serving",
    ],
    method: [
      { title: "Bloom garlic", text: "Cook garlic gently in olive oil until fragrant but not brown." },
      { title: "Simmer", text: "Add beans, tomatoes, stock and herbs. Mash ½ cup beans against the skillet and simmer 8 minutes." },
      { title: "Finish", text: "Fold in greens, add Parmesan and black pepper, then serve with toast." },
    ],
    finishCue: "The liquid becomes a creamy spoon-coating sauce and greens are tender.",
    swap: "Use nutritional yeast and vegan Parmesan for a dairy-free version.",
  },
  {
    id: "broccoli-cheddar-frittata",
    title: "Broccoli Cheddar Frittata",
    category: "Meatless",
    diet: "Vegetarian · high protein",
    minutes: 25,
    activeMinutes: 12,
    cookware: "Oven-safe skillet",
    servings: 4,
    image: "/images/recipes/30-minute-dinners-meatless.webp",
    imageAlt: "Broccoli cheddar frittata wedges with a green salad",
    whyFast: "Small broccoli florets cook on the stovetop while the broiler sets the top.",
    ingredients: [
      "8 large eggs",
      "¼ cup milk",
      "½ tsp fine salt and black pepper",
      "1 tbsp olive oil",
      "3 cups small broccoli florets",
      "3 scallions, sliced",
      "1 cup shredded sharp cheddar",
      "Green salad and toast for serving",
    ],
    method: [
      { title: "Mix eggs", text: "Whisk eggs, milk, salt and pepper just until uniform; avoid beating in a foam." },
      { title: "Cook vegetables", text: "Sauté broccoli in oil with 2 tablespoons water, covered, until crisp-tender. Add scallions." },
      { title: "Set", text: "Add eggs and cheddar, stir once, cook over medium-low until edges set, then broil briefly until the center is just firm." },
    ],
    finishCue: "Center reaches 160°F and no liquid egg remains when the skillet is gently shaken.",
    swap: "Use thawed chopped spinach squeezed very dry in place of broccoli.",
    safety: "USDA guidance lists 160°F (71°C) for egg dishes.",
  },
];

export const dinnerFaqs: FAQ[] = [
  {
    question: "What actually counts as a 30-minute dinner?",
    answer:
      "The clock should include normal chopping, heating the pan and finishing the dish—not only cook time. These recipes use common convenience ingredients such as canned beans, refrigerated pasta, microwave rice and prewashed greens where that makes the 30-minute promise realistic.",
  },
  {
    question: "How can I make weeknight cooking faster without meal prep?",
    answer:
      "Start the longest passive task first, cut ingredients to cook at similar speeds, use a wide pan, keep a trash bowl nearby and measure sauce ingredients while the pan preheats. A sharp knife and uncluttered counter save more time than rushing.",
  },
  {
    question: "Which 30-minute dinners use only one pan?",
    answer:
      "The lemon chicken, turkey-zucchini skillet, sausage gnocchi, egg-roll bowl, tomato tortellini, black bean tacos, chickpea curry and white bean skillet all keep cookware to one main vessel.",
  },
  {
    question: "What are the best vegetarian 30-minute dinners?",
    answer:
      "Creamy tomato tortellini, miso mushroom noodles, pesto gnocchi, Mediterranean chickpea bowls, black bean tacos, chickpea spinach curry, white bean skillet and broccoli cheddar frittata are meatless as written.",
  },
  {
    question: "How do I keep a quick dinner from tasting flat?",
    answer:
      "Use one concentrated savory ingredient—miso, tomato paste, Parmesan, pesto or soy sauce—then finish with acidity and a fresh aromatic. Adding lemon, lime, vinegar, scallions or herbs at the end keeps the flavor clear.",
  },
  {
    question: "What food temperatures should I check during fast cooking?",
    answer:
      "USDA guidance lists 165°F for poultry and leftovers, 160°F for ground meat and egg dishes, 145°F plus a 3-minute rest for whole cuts of beef and pork, and 145°F for fish. Shrimp should become pearly or white and opaque.",
  },
];

export const dinnerSources: SourceLink[] = [
  {
    label: "USDA FSIS — Safe Minimum Internal Temperature Chart",
    url: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/safe-temperature-chart",
    note: "Temperature targets used in the safety cues.",
  },
  {
    label: "FoodSafety.gov — Safe Minimum Internal Temperatures",
    url: "https://www.foodsafety.gov/food-safety-charts/safe-minimum-internal-temperatures",
    note: "Plain-language federal temperature table for meat, poultry, seafood, eggs and leftovers.",
  },
  {
    label: "USDA FSIS — Leftovers and Food Safety",
    url: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/leftovers-and-food-safety",
    note: "Cooling, refrigeration and reheating guidance.",
  },
  {
    label: "Google Search Central — Recipe structured data",
    url: "https://developers.google.com/search/docs/appearance/structured-data/recipe",
    note: "Recipe and ItemList markup guidance for the collection.",
  },
];

export const dinnerCategories = [
  "All",
  "Skillet",
  "Pasta & noodles",
  "Bowls",
  "Tacos & wraps",
  "Meatless",
] as const;
